######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 8 19:25:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . headers sources
INCLUDEPATH += . headers

QT += sql

# Input
HEADERS += headers/Window.h pages.h
SOURCES += sources/main.cpp Window.cpp pages.cpp
RESSOURCES += irm.qrc
